server:
  port: 9093

spring:
  main:
    banner-mode: 'off'
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL

logging:
  level:
    org:
      springframework: ERROR
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.datasource.username=sa
# spring.datasource.password=

# #spring.datasource.url=jdbc:postgresql://localhost:5432/adsis4s2020
# #spring.datasource.username=postgres
# #spring.datasource.password=postgres

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# #logging.level.org.hibernate.SQL=DEBUG
# #logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# server.port=9093

# logging.level.root=ERROR
# logging.level.org.springframework.web=ERROR
# logging.level.org.hibernate=ERROR
# logging.level.org.springframework.web.client.RestTemplate=ERROR
